"use strict";

const languageFromlang3 = (lang3) => {
    let lang = null;
    if(lang3) {
        lang3 = lang3.trim();
        if (lang3.length > 0) {
            lang = LANGUAGE_BY_CODE[lang3];
            if (lang instanceof Object)
                lang = lang.lang1 || lang.lang2;
        }
    }
    return lang;
};

const localeFromLang3 = (lang3) => {
    let locale = null;
    if(lang3) {
        lang3 = lang3.trim();
        if (lang3.length > 0) {
            const language = languageFromlang3(lang3);
            locale = LOCALE_BY_LANGUAGE[language];
        }
    }
    return locale;
};

const lang3FromLocale = (locale) => {
    let lang3 = null;
    if(locale) {
        locale = locale.trim();
        if (locale) {
            const language = LANGUAGE_BY_LOCALE[locale];
            lang3 = CODE_BY_LANGUAGE[language] || CODE_BY_LANGUAGE[language.split(' ')[0]];
        }
    }
    return lang3;
};

const LANGUAGE_BY_LOCALE = {
    af_NA: "Afrikaans (Namibia)",
    af_ZA: "Afrikaans (South Africa)",
    af: "Afrikaans",
    ak_GH: "Akan (Ghana)",
    ak: "Akan",
    sq_AL: "Albanian (Albania)",
    sq: "Albanian",
    am_ET: "Amharic (Ethiopia)",
    am: "Amharic",
    ar_DZ: "Arabic (Algeria)",
    ar_BH: "Arabic (Bahrain)",
    ar_EG: "Arabic (Egypt)",
    ar_IQ: "Arabic (Iraq)",
    ar_JO: "Arabic (Jordan)",
    ar_KW: "Arabic (Kuwait)",
    ar_LB: "Arabic (Lebanon)",
    ar_LY: "Arabic (Libya)",
    ar_MA: "Arabic (Morocco)",
    ar_OM: "Arabic (Oman)",
    ar_QA: "Arabic (Qatar)",
    ar_SA: "Arabic (Saudi Arabia)",
    ar_SD: "Arabic (Sudan)",
    ar_SY: "Arabic (Syria)",
    ar_TN: "Arabic (Tunisia)",
    ar_AE: "Arabic (United Arab Emirates)",
    ar_YE: "Arabic (Yemen)",
    ar: "Arabic",
    hy_AM: "Armenian (Armenia)",
    hy: "Armenian",
    as_IN: "Assamese (India)",
    as: "Assamese",
    asa_TZ: "Asu (Tanzania)",
    asa: "Asu",
    az_Cyrl: "Azerbaijani (Cyrillic)",
    az_Cyrl_AZ: "Azerbaijani (Cyrillic, Azerbaijan)",
    az_Latn: "Azerbaijani (Latin)",
    az_Latn_AZ: "Azerbaijani (Latin, Azerbaijan)",
    az: "Azerbaijani",
    bm_ML: "Bambara (Mali)",
    bm: "Bambara",
    eu_ES: "Basque (Spain)",
    eu: "Basque",
    be_BY: "Belarusian (Belarus)",
    be: "Belarusian",
    bem_ZM: "Bemba (Zambia)",
    bem: "Bemba",
    bez_TZ: "Bena (Tanzania)",
    bez: "Bena",
    bn_BD: "Bengali (Bangladesh)",
    bn_IN: "Bengali (India)",
    bn: "Bengali",
    bs_BA: "Bosnian (Bosnia and Herzegovina)",
    bs: "Bosnian",
    bg_BG: "Bulgarian (Bulgaria)",
    bg: "Bulgarian",
    my_MM: "Burmese (Myanmar [Burma])",
    my: "Burmese",
    ca_ES: "Catalan (Spain)",
    ca: "Catalan",
    tzm_Latn: "Central Morocco Tamazight (Latin)",
    tzm_Latn_MA: "Central Morocco Tamazight (Latin, Morocco)",
    tzm: "Central Morocco Tamazight",
    chr_US: "Cherokee (United States)",
    chr: "Cherokee",
    cgg_UG: "Chiga (Uganda)",
    cgg: "Chiga",
    zh_Hans: "Chinese (Simplified Han)",
    zh_Hans_CN: "Chinese (Simplified Han, China)",
    zh_Hans_HK: "Chinese (Simplified Han, Hong Kong SAR China)",
    zh_Hans_MO: "Chinese (Simplified Han, Macau SAR China)",
    zh_Hans_SG: "Chinese (Simplified Han, Singapore)",
    zh_Hant: "Chinese (Traditional Han)",
    zh_Hant_HK: "Chinese (Traditional Han, Hong Kong SAR China)",
    zh_Hant_MO: "Chinese (Traditional Han, Macau SAR China)",
    zh_Hant_TW: "Chinese (Traditional Han, Taiwan)",
    zh: "Chinese",
    kw_GB: "Cornish (United Kingdom)",
    kw: "Cornish",
    hr_HR: "Croatian (Croatia)",
    hr: "Croatian",
    cs_CZ: "Czech (Czech Republic)",
    cs: "Czech",
    da_DK: "Danish (Denmark)",
    da: "Danish",
    nl_BE: "Dutch (Belgium)",
    nl_NL: "Dutch (Netherlands)",
    nl: "Dutch",
    ebu_KE: "Embu (Kenya)",
    ebu: "Embu",
    en_AS: "English (American Samoa)",
    en_AU: "English (Australia)",
    en_BE: "English (Belgium)",
    en_BZ: "English (Belize)",
    en_BW: "English (Botswana)",
    en_CA: "English (Canada)",
    en_GU: "English (Guam)",
    en_HK: "English (Hong Kong SAR China)",
    en_IN: "English (India)",
    en_IE: "English (Ireland)",
    en_JM: "English (Jamaica)",
    en_MT: "English (Malta)",
    en_MH: "English (Marshall Islands)",
    en_MU: "English (Mauritius)",
    en_NA: "English (Namibia)",
    en_NZ: "English (New Zealand)",
    en_MP: "English (Northern Mariana Islands)",
    en_PK: "English (Pakistan)",
    en_PH: "English (Philippines)",
    en_SG: "English (Singapore)",
    en_ZA: "English (South Africa)",
    en_TT: "English (Trinidad and Tobago)",
    en_UM: "English (U.S. Minor Outlying Islands)",
    en_VI: "English (U.S. Virgin Islands)",
    en_GB: "English (United Kingdom)",
    en_US: "English (United States)",
    en_ZW: "English (Zimbabwe)",
    en: "English",
    eo: "Esperanto",
    et_EE: "Estonian (Estonia)",
    et: "Estonian",
    ee_GH: "Ewe (Ghana)",
    ee_TG: "Ewe (Togo)",
    ee: "Ewe",
    fo_FO: "Faroese (Faroe Islands)",
    fo: "Faroese",
    fil_PH: "Filipino (Philippines)",
    fil: "Filipino",
    fi_FI: "Finnish (Finland)",
    fi: "Finnish",
    fr_BE: "French (Belgium)",
    fr_BJ: "French (Benin)",
    fr_BF: "French (Burkina Faso)",
    fr_BI: "French (Burundi)",
    fr_CM: "French (Cameroon)",
    fr_CA: "French (Canada)",
    fr_CF: "French (Central African Republic)",
    fr_TD: "French (Chad)",
    fr_KM: "French (Comoros)",
    fr_CG: "French (Congo - Brazzaville)",
    fr_CD: "French (Congo - Kinshasa)",
    fr_CI: "French (Côte d’Ivoire)",
    fr_DJ: "French (Djibouti)",
    fr_GQ: "French (Equatorial Guinea)",
    fr_FR: "French (France)",
    fr_GA: "French (Gabon)",
    fr_GP: "French (Guadeloupe)",
    fr_GN: "French (Guinea)",
    fr_LU: "French (Luxembourg)",
    fr_MG: "French (Madagascar)",
    fr_ML: "French (Mali)",
    fr_MQ: "French (Martinique)",
    fr_MC: "French (Monaco)",
    fr_NE: "French (Niger)",
    fr_RW: "French (Rwanda)",
    fr_RE: "French (Réunion)",
    fr_BL: "French (Saint Barthélemy)",
    fr_MF: "French (Saint Martin)",
    fr_SN: "French (Senegal)",
    fr_CH: "French (Switzerland)",
    fr_TG: "French (Togo)",
    fr: "French",
    ff_SN: "Fulah (Senegal)",
    ff: "Fulah",
    gl_ES: "Galician (Spain)",
    gl: "Galician",
    lg_UG: "Ganda (Uganda)",
    lg: "Ganda",
    ka_GE: "Georgian (Georgia)",
    ka: "Georgian",
    de_AT: "German (Austria)",
    de_BE: "German (Belgium)",
    de_DE: "German (Germany)",
    de_LI: "German (Liechtenstein)",
    de_LU: "German (Luxembourg)",
    de_CH: "German (Switzerland)",
    de: "German",
    el_CY: "Greek (Cyprus)",
    el_GR: "Greek (Greece)",
    el: "Greek",
    gu_IN: "Gujarati (India)",
    gu: "Gujarati",
    guz_KE: "Gusii (Kenya)",
    guz: "Gusii",
    ha_Latn: "Hausa (Latin)",
    ha_Latn_GH: "Hausa (Latin, Ghana)",
    ha_Latn_NE: "Hausa (Latin, Niger)",
    ha_Latn_NG: "Hausa (Latin, Nigeria)",
    ha: "Hausa",
    haw_US: "Hawaiian (United States)",
    haw: "Hawaiian",
    he_IL: "Hebrew (Israel)",
    he: "Hebrew",
    hi_IN: "Hindi (India)",
    hi: "Hindi",
    hu_HU: "Hungarian (Hungary)",
    hu: "Hungarian",
    is_IS: "Icelandic (Iceland)",
    is: "Icelandic",
    ig_NG: "Igbo (Nigeria)",
    ig: "Igbo",
    id_ID: "Indonesian (Indonesia)",
    id: "Indonesian",
    ga_IE: "Irish (Ireland)",
    ga: "Irish",
    it_IT: "Italian (Italy)",
    it_CH: "Italian (Switzerland)",
    it: "Italian",
    ja_JP: "Japanese (Japan)",
    ja: "Japanese",
    kea_CV: "Kabuverdianu (Cape Verde)",
    kea: "Kabuverdianu",
    kab_DZ: "Kabyle (Algeria)",
    kab: "Kabyle",
    kl_GL: "Kalaallisut (Greenland)",
    kl: "Kalaallisut",
    kln_KE: "Kalenjin (Kenya)",
    kln: "Kalenjin",
    kam_KE: "Kamba (Kenya)",
    kam: "Kamba",
    kn_IN: "Kannada (India)",
    kn: "Kannada",
    kk_Cyrl: "Kazakh (Cyrillic)",
    kk_Cyrl_KZ: "Kazakh (Cyrillic, Kazakhstan)",
    kk: "Kazakh",
    km_KH: "Khmer (Cambodia)",
    km: "Khmer",
    ki_KE: "Kikuyu (Kenya)",
    ki: "Kikuyu",
    rw_RW: "Kinyarwanda (Rwanda)",
    rw: "Kinyarwanda",
    kok_IN: "Konkani (India)",
    kok: "Konkani",
    ko_KR: "Korean (South Korea)",
    ko: "Korean",
    khq_ML: "Koyra Chiini (Mali)",
    khq: "Koyra Chiini",
    ses_ML: "Koyraboro Senni (Mali)",
    ses: "Koyraboro Senni",
    lag_TZ: "Langi (Tanzania)",
    lag: "Langi",
    lv_LV: "Latvian (Latvia)",
    lv: "Latvian",
    lt_LT: "Lithuanian (Lithuania)",
    lt: "Lithuanian",
    luo_KE: "Luo (Kenya)",
    luo: "Luo",
    luy_KE: "Luyia (Kenya)",
    luy: "Luyia",
    mk_MK: "Macedonian (Macedonia)",
    mk: "Macedonian",
    jmc_TZ: "Machame (Tanzania)",
    jmc: "Machame",
    kde_TZ: "Makonde (Tanzania)",
    kde: "Makonde",
    mg_MG: "Malagasy (Madagascar)",
    mg: "Malagasy",
    ms_BN: "Malay (Brunei)",
    ms_MY: "Malay (Malaysia)",
    ms: "Malay",
    ml_IN: "Malayalam (India)",
    ml: "Malayalam",
    mt_MT: "Maltese (Malta)",
    mt: "Maltese",
    gv_GB: "Manx (United Kingdom)",
    gv: "Manx",
    mr_IN: "Marathi (India)",
    mr: "Marathi",
    mas_KE: "Masai (Kenya)",
    mas_TZ: "Masai (Tanzania)",
    mas: "Masai",
    mer_KE: "Meru (Kenya)",
    mer: "Meru",
    mfe_MU: "Morisyen (Mauritius)",
    mfe: "Morisyen",
    naq_NA: "Nama (Namibia)",
    naq: "Nama",
    ne_IN: "Nepali (India)",
    ne_NP: "Nepali (Nepal)",
    ne: "Nepali",
    nd_ZW: "North Ndebele (Zimbabwe)",
    nd: "North Ndebele",
    nb_NO: "Norwegian Bokmål (Norway)",
    nb: "Norwegian Bokmål",
    nn_NO: "Norwegian Nynorsk (Norway)",
    nn: "Norwegian Nynorsk",
    nyn_UG: "Nyankole (Uganda)",
    nyn: "Nyankole",
    or_IN: "Oriya (India)",
    or: "Oriya",
    om_ET: "Oromo (Ethiopia)",
    om_KE: "Oromo (Kenya)",
    om: "Oromo",
    ps_AF: "Pashto (Afghanistan)",
    ps: "Pashto",
    fa_AF: "Persian (Afghanistan)",
    fa_IR: "Persian (Iran)",
    fa: "Persian",
    pl_PL: "Polish (Poland)",
    pl: "Polish",
    pt_BR: "Portuguese (Brazil)",
    pt_GW: "Portuguese (Guinea-Bissau)",
    pt_MZ: "Portuguese (Mozambique)",
    pt_PT: "Portuguese (Portugal)",
    pt: "Portuguese",
    pa_Arab: "Punjabi (Arabic)",
    pa_Arab_PK: "Punjabi (Arabic, Pakistan)",
    pa_Guru: "Punjabi (Gurmukhi)",
    pa_Guru_IN: "Punjabi (Gurmukhi, India)",
    pa: "Punjabi",
    ro_MD: "Romanian (Moldova)",
    ro_RO: "Romanian (Romania)",
    ro: "Romanian",
    rm_CH: "Romansh (Switzerland)",
    rm: "Romansh",
    rof_TZ: "Rombo (Tanzania)",
    rof: "Rombo",
    ru_MD: "Russian (Moldova)",
    ru_RU: "Russian (Russia)",
    ru_UA: "Russian (Ukraine)",
    ru: "Russian",
    rwk_TZ: "Rwa (Tanzania)",
    rwk: "Rwa",
    saq_KE: "Samburu (Kenya)",
    saq: "Samburu",
    sg_CF: "Sango (Central African Republic)",
    sg: "Sango",
    seh_MZ: "Sena (Mozambique)",
    seh: "Sena",
    sr_Cyrl: "Serbian (Cyrillic)",
    sr_Cyrl_BA: "Serbian (Cyrillic, Bosnia and Herzegovina)",
    sr_Cyrl_ME: "Serbian (Cyrillic, Montenegro)",
    sr_Cyrl_RS: "Serbian (Cyrillic, Serbia)",
    sr_Latn: "Serbian (Latin)",
    sr_Latn_BA: "Serbian (Latin, Bosnia and Herzegovina)",
    sr_Latn_ME: "Serbian (Latin, Montenegro)",
    sr_Latn_RS: "Serbian (Latin, Serbia)",
    sr: "Serbian",
    sn_ZW: "Shona (Zimbabwe)",
    sn: "Shona",
    ii_CN: "Sichuan Yi (China)",
    ii: "Sichuan Yi",
    si_LK: "Sinhala (Sri Lanka)",
    si: "Sinhala",
    sk_SK: "Slovak (Slovakia)",
    sk: "Slovak",
    sl_SI: "Slovenian (Slovenia)",
    sl: "Slovenian",
    xog_UG: "Soga (Uganda)",
    xog: "Soga",
    so_DJ: "Somali (Djibouti)",
    so_ET: "Somali (Ethiopia)",
    so_KE: "Somali (Kenya)",
    so_SO: "Somali (Somalia)",
    so: "Somali",
    es_AR: "Spanish (Argentina)",
    es_BO: "Spanish (Bolivia)",
    es_CL: "Spanish (Chile)",
    es_CO: "Spanish (Colombia)",
    es_CR: "Spanish (Costa Rica)",
    es_DO: "Spanish (Dominican Republic)",
    es_EC: "Spanish (Ecuador)",
    es_SV: "Spanish (El Salvador)",
    es_GQ: "Spanish (Equatorial Guinea)",
    es_GT: "Spanish (Guatemala)",
    es_HN: "Spanish (Honduras)",
    es_419: "Spanish (Latin America)",
    es_MX: "Spanish (Mexico)",
    es_NI: "Spanish (Nicaragua)",
    es_PA: "Spanish (Panama)",
    es_PY: "Spanish (Paraguay)",
    es_PE: "Spanish (Peru)",
    es_PR: "Spanish (Puerto Rico)",
    es_ES: "Spanish (Spain)",
    es_US: "Spanish (United States)",
    es_UY: "Spanish (Uruguay)",
    es_VE: "Spanish (Venezuela)",
    es: "Spanish",
    sw_KE: "Swahili (Kenya)",
    sw_TZ: "Swahili (Tanzania)",
    sw: "Swahili",
    sv_FI: "Swedish (Finland)",
    sv_SE: "Swedish (Sweden)",
    sv: "Swedish",
    gsw_CH: "Swiss German (Switzerland)",
    gsw: "Swiss German",
    shi_Latn: "Tachelhit (Latin)",
    shi_Latn_MA: "Tachelhit (Latin, Morocco)",
    shi_Tfng: "Tachelhit (Tifinagh)",
    shi_Tfng_MA: "Tachelhit (Tifinagh, Morocco)",
    shi: "Tachelhit",
    dav_KE: "Taita (Kenya)",
    dav: "Taita",
    ta_IN: "Tamil (India)",
    ta_LK: "Tamil (Sri Lanka)",
    ta: "Tamil",
    te_IN: "Telugu (India)",
    te: "Telugu",
    teo_KE: "Teso (Kenya)",
    teo_UG: "Teso (Uganda)",
    teo: "Teso",
    th_TH: "Thai (Thailand)",
    th: "Thai",
    bo_CN: "Tibetan (China)",
    bo_IN: "Tibetan (India)",
    bo: "Tibetan",
    ti_ER: "Tigrinya (Eritrea)",
    ti_ET: "Tigrinya (Ethiopia)",
    ti: "Tigrinya",
    to_TO: "Tonga (Tonga)",
    to: "Tonga",
    tr_TR: "Turkish (Turkey)",
    tr: "Turkish",
    uk_UA: "Ukrainian (Ukraine)",
    uk: "Ukrainian",
    ur_IN: "Urdu (India)",
    ur_PK: "Urdu (Pakistan)",
    ur: "Urdu",
    uz_Arab: "Uzbek (Arabic)",
    uz_Arab_AF: "Uzbek (Arabic, Afghanistan)",
    uz_Cyrl: "Uzbek (Cyrillic)",
    uz_Cyrl_UZ: "Uzbek (Cyrillic, Uzbekistan)",
    uz_Latn: "Uzbek (Latin)",
    uz_Latn_UZ: "Uzbek (Latin, Uzbekistan)",
    uz: "Uzbek",
    vi_VN: "Vietnamese (Vietnam)",
    vi: "Vietnamese",
    vun_TZ: "Vunjo (Tanzania)",
    vun: "Vunjo",
    cy_GB: "Welsh (United Kingdom)",
    cy: "Welsh",
    yo_NG: "Yoruba (Nigeria)",
    yo: "Yoruba",
    zu_ZA: "Zulu (South Africa)",
    zu: "Zulu"
};

const LOCALE_BY_LANGUAGE = {
    Afrikaans_Namibia: "af-NA",
    Afrikaans_South_Africa: "af-ZA",
    Afrikaans: "af",
    Akan_Ghana: "ak-GH",
    Akan: "ak",
    Albanian_Albania: "sq-AL",
    Albanian: "sq",
    Amharic_Ethiopia: "am-ET",
    Amharic: "am",
    Arabic_Algeria: "ar-DZ",
    Arabic_Bahrain: "ar-BH",
    Arabic_Egypt: "ar-EG",
    Arabic_Iraq: "ar-IQ",
    Arabic_Jordan: "ar-JO",
    Arabic_Kuwait: "ar-KW",
    Arabic_Lebanon: "ar-LB",
    Arabic_Libya: "ar-LY",
    Arabic_Morocco: "ar-MA",
    Arabic_Oman: "ar-OM",
    Arabic_Qatar: "ar-QA",
    Arabic_Saudi_Arabia: "ar-SA",
    Arabic_Sudan: "ar-SD",
    Arabic_Syria: "ar-SY",
    Arabic_Tunisia: "ar-TN",
    Arabic_United_Arab_Emirates: "ar-AE",
    Arabic_Yemen: "ar-YE",
    Arabic: "ar",
    Armenian_Armenia: "hy-AM",
    Armenian: "hy",
    Assamese_India: "as-IN",
    Assamese: "as",
    Asu_Tanzania: "asa-TZ",
    Asu: "asa",
    Azerbaijani_Cyrillic: "az-Cyrl",
    Azerbaijani_Cyrillic_Azerbaijan: "az-Cyrl-AZ",
    Azerbaijani_Latin: "az-Latn",
    Azerbaijani_Latin_Azerbaijan: "az-Latn-AZ",
    Azerbaijani: "az",
    Bambara_Mali: "bm-ML",
    Bambara: "bm",
    Basque_Spain: "eu-ES",
    Basque: "eu",
    Belarusian_Belarus: "be-BY",
    Belarusian: "be",
    Bemba_Zambia: "bem-ZM",
    Bemba: "bem",
    Bena_Tanzania: "bez-TZ",
    Bena: "bez",
    Bengali_Bangladesh: "bn-BD",
    Bengali_India: "bn-IN",
    Bengali: "bn",
    Bosnian_Bosnia_and_Herzegovina: "bs-BA",
    Bosnian: "bs",
    Bulgarian_Bulgaria: "bg-BG",
    Bulgarian: "bg",
    Burmese_Myanmar_Burma: "my-MM",
    Burmese: "my",
    Catalan_Spain: "ca-ES",
    Catalan: "ca",
    Central_Morocco_Tamazight_Latin: "tzm-Latn",
    Central_Morocco_Tamazight_Latin_Morocco: "tzm-Latn-MA",
    Central_Morocco_Tamazight: "tzm",
    Cherokee_United_States: "chr-US",
    Cherokee: "chr",
    Chiga_Uganda: "cgg-UG",
    Chiga: "cgg",
    SimplifiedChinese: "zh-Hans",
    Chinese_Simplified_Han: "zh-Hans",
    Chinese_Simplified_Han_China: "zh-Hans-CN",
    Chinese_Simplified_Han_Hong_Kong_SAR_China: "zh-Hans-HK",
    Chinese_Simplified_Han_Macau_SAR_China: "zh-Hans-MO",
    Chinese_Simplified_Han_Singapore: "zh-Hans-SG",
    Chinese_Traditional_Han: "zh-Hant",
    Chinese_Traditional_Han_Hong_Kong_SAR_China: "zh-Hant-HK",
    Chinese_Traditional_Han_Macau_SAR_China: "zh-Hant-MO",
    Chinese_Traditional_Han_Taiwan: "zh-Hant-TW",
    Chinese: "zh",
    Cornish_United_Kingdom: "kw-GB",
    Cornish: "kw",
    Croatian_Croatia: "hr-HR",
    Croatian: "hr",
    Czech_Czech_Republic: "cs-CZ",
    Czech: "cs",
    Danish_Denmark: "da-DK",
    Danish: "da",
    Dutch_Belgium: "nl-BE",
    Dutch_Netherlands: "nl-NL",
    Dutch: "nl",
    Embu_Kenya: "ebu-KE",
    Embu: "ebu",
    English_American_Samoa: "en-AS",
    English_Australia: "en-AU",
    English_Belgium: "en-BE",
    English_Belize: "en-BZ",
    English_Botswana: "en-BW",
    English_Canada: "en-CA",
    English_Guam: "en-GU",
    English_Hong_Kong_SAR_China: "en-HK",
    English_India: "en-IN",
    English_Ireland: "en-IE",
    English_Jamaica: "en-JM",
    English_Malta: "en-MT",
    English_Marshall_Islands: "en-MH",
    English_Mauritius: "en-MU",
    English_Namibia: "en-NA",
    English_New_Zealand: "en-NZ",
    English_Northern_Mariana_Islands: "en-MP",
    English_Pakistan: "en-PK",
    English_Philippines: "en-PH",
    English_Singapore: "en-SG",
    English_South_Africa: "en-ZA",
    English_Trinidad_and_Tobago: "en-TT",
    English_US_Minor_Outlying_Islands: "en-UM",
    English_US_Virgin_Islands: "en-VI",
    English_United_Kingdom: "en-GB",
    English_United_States: "en-US",
    English_Zimbabwe: "en-ZW",
    English: "en",
    Esperanto: "eo",
    Estonian_Estonia: "et-EE",
    Estonian: "et",
    Ewe_Ghana: "ee-GH",
    Ewe_Togo: "ee-TG",
    Ewe: "ee",
    Faroese_Faroe_Islands: "fo-FO",
    Faroese: "fo",
    Filipino_Philippines: "fil-PH",
    Filipino: "fil",
    Finnish_Finland: "fi-FI",
    Finnish: "fi",
    French_Belgium: "fr-BE",
    French_Benin: "fr-BJ",
    French_Burkina_Faso: "fr-BF",
    French_Burundi: "fr-BI",
    French_Cameroon: "fr-CM",
    French_Canada: "fr-CA",
    French_Central_African_Republic: "fr-CF",
    French_Chad: "fr-TD",
    French_Comoros: "fr-KM",
    French_Congo_Brazzaville: "fr-CG",
    French_Congo_Kinshasa: "fr-CD",
    French_Cote_d_Ivoire: "fr-CI",
    French_Djibouti: "fr-DJ",
    French_Equatorial_Guinea: "fr-GQ",
    French_France: "fr-FR",
    French_Gabon: "fr-GA",
    French_Guadeloupe: "fr-GP",
    French_Guinea: "fr-GN",
    French_Luxembourg: "fr-LU",
    French_Madagascar: "fr-MG",
    French_Mali: "fr-ML",
    French_Martinique: "fr-MQ",
    French_Monaco: "fr-MC",
    French_Niger: "fr-NE",
    French_Rwanda: "fr-RW",
    French_Reunion: "fr-RE",
    French_Saint_Barthelemy: "fr-BL",
    French_Saint_Martin: "fr-MF",
    French_Senegal: "fr-SN",
    French_Switzerland: "fr-CH",
    French_Togo: "fr-TG",
    French: "fr",
    Fulah_Senegal: "ff-SN",
    Fulah: "ff",
    Galician_Spain: "gl-ES",
    Galician: "gl",
    Ganda_Uganda: "lg-UG",
    Ganda: "lg",
    Georgian_Georgia: "ka-GE",
    Georgian: "ka",
    German_Austria: "de-AT",
    German_Belgium: "de-BE",
    German_Germany: "de-DE",
    German_Liechtenstein: "de-LI",
    German_Luxembourg: "de-LU",
    German_Switzerland: "de-CH",
    German: "de",
    Greek_Cyprus: "el-CY",
    Greek_Greece: "el-GR",
    Greek: "el",
    Gujarati_India: "gu-IN",
    Gujarati: "gu",
    Gusii_Kenya: "guz-KE",
    Gusii: "guz",
    Hausa_Latin: "ha-Latn",
    Hausa_Latin_Ghana: "ha-Latn-GH",
    Hausa_Latin_Niger: "ha-Latn-NE",
    Hausa_Latin_Nigeria: "ha-Latn-NG",
    Hausa: "ha",
    Hawaiian_United_States: "haw-US",
    Hawaiian: "haw",
    Hebrew_Israel: "he-IL",
    Hebrew: "he",
    Hindi_India: "hi-IN",
    Hindi: "hi",
    Hungarian_Hungary: "hu-HU",
    Hungarian: "hu",
    Icelandic_Iceland: "is-IS",
    Icelandic: "is",
    Igbo_Nigeria: "ig-NG",
    Igbo: "ig",
    Indonesian_Indonesia: "id-ID",
    Indonesian: "id",
    Irish_Ireland: "ga-IE",
    Irish: "ga",
    Italian_Italy: "it-IT",
    Italian_Switzerland: "it-CH",
    Italian: "it",
    Japanese_Japan: "ja-JP",
    Japanese: "ja",
    Kabuverdianu_Cape_Verde: "kea-CV",
    Kabuverdianu: "kea",
    Kabyle_Algeria: "kab-DZ",
    Kabyle: "kab",
    Kalaallisut_Greenland: "kl-GL",
    Kalaallisut: "kl",
    Kalenjin_Kenya: "kln-KE",
    Kalenjin: "kln",
    Kamba_Kenya: "kam-KE",
    Kamba: "kam",
    Kannada_India: "kn-IN",
    Kannada: "kn",
    Kazakh_Cyrillic: "kk-Cyrl",
    Kazakh_Cyrillic_Kazakhstan: "kk-Cyrl-KZ",
    Kazakh: "kk",
    Khmer_Cambodia: "km-KH",
    Khmer: "km",
    Kikuyu_Kenya: "ki-KE",
    Kikuyu: "ki",
    Kinyarwanda_Rwanda: "rw-RW",
    Kinyarwanda: "rw",
    Konkani_India: "kok-IN",
    Konkani: "kok",
    Korean_South_Korea: "ko-KR",
    Korean: "ko",
    Koyra_Chiini_Mali: "khq-ML",
    Koyra_Chiini: "khq",
    Koyraboro_Senni_Mali: "ses-ML",
    Koyraboro_Senni: "ses",
    Langi_Tanzania: "lag-TZ",
    Langi: "lag",
    Latvian_Latvia: "lv-LV",
    Latvian: "lv",
    Lithuanian_Lithuania: "lt-LT",
    Lithuanian: "lt",
    Luo_Kenya: "luo-KE",
    Luo: "luo",
    Luyia_Kenya: "luy-KE",
    Luyia: "luy",
    Macedonian_Macedonia: "mk-MK",
    Macedonian: "mk",
    Machame_Tanzania: "jmc-TZ",
    Machame: "jmc",
    Makonde_Tanzania: "kde-TZ",
    Makonde: "kde",
    Malagasy_Madagascar: "mg-MG",
    Malagasy: "mg",
    Malay_Brunei: "ms-BN",
    Malay_Malaysia: "ms-MY",
    Malay: "ms",
    Malayalam_India: "ml-IN",
    Malayalam: "ml",
    Maltese_Malta: "mt-MT",
    Maltese: "mt",
    Manx_United_Kingdom: "gv-GB",
    Manx: "gv",
    Marathi_India: "mr-IN",
    Marathi: "mr",
    Masai_Kenya: "mas-KE",
    Masai_Tanzania: "mas-TZ",
    Masai: "mas",
    Meru_Kenya: "mer-KE",
    Meru: "mer",
    Morisyen_Mauritius: "mfe-MU",
    Morisyen: "mfe",
    Nama_Namibia: "naq-NA",
    Nama: "naq",
    Nepali_India: "ne-IN",
    Nepali_Nepal: "ne-NP",
    Nepali: "ne",
    North_Ndebele_Zimbabwe: "nd-ZW",
    North_Ndebele: "nd",
    Norwegian_Bokmal_Norway: "nb-NO",
    Norwegian_Bokmal: "nb",
    Norwegian_Nynorsk_Norway: "nn-NO",
    Norwegian_Nynorsk: "nn",
    Nyankole_Uganda: "nyn-UG",
    Nyankole: "nyn",
    Oriya_India: "or-IN",
    Oriya: "or",
    Oromo_Ethiopia: "om-ET",
    Oromo_Kenya: "om-KE",
    Oromo: "om",
    Pashto_Afghanistan: "ps-AF",
    Pashto: "ps",
    Persian_Afghanistan: "fa-AF",
    Persian_Iran: "fa-IR",
    Persian: "fa",
    Polish_Poland: "pl-PL",
    Polish: "pl",
    Portuguese_Brazil: "pt-BR",
    Portuguese_Guinea_Bissau: "pt-GW",
    Portuguese_Mozambique: "pt-MZ",
    Portuguese_Portugal: "pt-PT",
    Portuguese: "pt",
    Punjabi_Arabic: "pa-Arab",
    Punjabi_Arabic_Pakistan: "pa-Arab-PK",
    Punjabi_Gurmukhi: "pa-Guru",
    Punjabi_Gurmukhi_India: "pa-Guru-IN",
    Punjabi: "pa",
    Romanian_Moldova: "ro-MD",
    Romanian_Romania: "ro-RO",
    Romanian: "ro",
    Romansh_Switzerland: "rm-CH",
    Romansh: "rm",
    Rombo_Tanzania: "rof-TZ",
    Rombo: "rof",
    Russian_Moldova: "ru-MD",
    Russian_Russia: "ru-RU",
    Russian_Ukraine: "ru-UA",
    Russian: "ru",
    Rwa_Tanzania: "rwk-TZ",
    Rwa: "rwk",
    Samburu_Kenya: "saq-KE",
    Samburu: "saq",
    Sango_Central_African_Republic: "sg-CF",
    Sango: "sg",
    Sena_Mozambique: "seh-MZ",
    Sena: "seh",
    Serbian_Cyrillic: "sr-Cyrl",
    Serbian_Cyrillic_Bosnia_and_Herzegovina: "sr-Cyrl-BA",
    Serbian_Cyrillic_Montenegro: "sr-Cyrl-ME",
    Serbian_Cyrillic_Serbia: "sr-Cyrl-RS",
    Serbian_Latin: "sr-Latn",
    Serbian_Latin_Bosnia_and_Herzegovina: "sr-Latn-BA",
    Serbian_Latin_Montenegro: "sr-Latn-ME",
    Serbian_Latin_Serbia: "sr-Latn-RS",
    Serbian: "sr",
    Shona_Zimbabwe: "sn-ZW",
    Shona: "sn",
    Sichuan_Yi_China: "ii-CN",
    Sichuan_Yi: "ii",
    Sinhala_Sri_Lanka: "si-LK",
    Sinhala: "si",
    Slovak_Slovakia: "sk-SK",
    Slovak: "sk",
    Slovenian_Slovenia: "sl-SI",
    Slovenian: "sl",
    Soga_Uganda: "xog-UG",
    Soga: "xog",
    Somali_Djibouti: "so-DJ",
    Somali_Ethiopia: "so-ET",
    Somali_Kenya: "so-KE",
    Somali_Somalia: "so-SO",
    Somali: "so",
    Spanish_Argentina: "es-AR",
    Spanish_Bolivia: "es-BO",
    Spanish_Chile: "es-CL",
    Spanish_Colombia: "es-CO",
    Spanish_Costa_Rica: "es-CR",
    Spanish_Dominican_Republic: "es-DO",
    Spanish_Ecuador: "es-EC",
    Spanish_El_Salvador: "es-SV",
    Spanish_Equatorial_Guinea: "es-GQ",
    Spanish_Guatemala: "es-GT",
    Spanish_Honduras: "es-HN",
    Spanish_Latin_America: "es-419",
    Spanish_Mexico: "es-MX",
    Spanish_Nicaragua: "es-NI",
    Spanish_Panama: "es-PA",
    Spanish_Paraguay: "es-PY",
    Spanish_Peru: "es-PE",
    Spanish_Puerto_Rico: "es-PR",
    Spanish_Spain: "es-ES",
    Spanish_United_States: "es-US",
    Spanish_Uruguay: "es-UY",
    Spanish_Venezuela: "es-VE",
    Spanish: "es",
    Swahili_Kenya: "sw-KE",
    Swahili_Tanzania: "sw-TZ",
    Swahili: "sw",
    Swedish_Finland: "sv-FI",
    Swedish_Sweden: "sv-SE",
    Swedish: "sv",
    Swiss_German_Switzerland: "gsw-CH",
    Swiss_German: "gsw",
    Tachelhit_Latin: "shi-Latn",
    Tachelhit_Latin_Morocco: "shi-Latn-MA",
    Tachelhit_Tifinagh: "shi-Tfng",
    Tachelhit_Tifinagh_Morocco: "shi-Tfng-MA",
    Tachelhit: "shi",
    Taita_Kenya: "dav-KE",
    Taita: "dav",
    Tamil_India: "ta-IN",
    Tamil_Sri_Lanka: "ta-LK",
    Tamil: "ta",
    Telugu_India: "te-IN",
    Telugu: "te",
    Teso_Kenya: "teo-KE",
    Teso_Uganda: "teo-UG",
    Teso: "teo",
    Thai_Thailand: "th-TH",
    Thai: "th",
    Tibetan_China: "bo-CN",
    Tibetan_India: "bo-IN",
    Tibetan: "bo",
    Tigrinya_Eritrea: "ti-ER",
    Tigrinya_Ethiopia: "ti-ET",
    Tigrinya: "ti",
    Tonga_Tonga: "to-TO",
    Tonga: "to",
    Turkish_Turkey: "tr-TR",
    Turkish: "tr",
    Ukrainian_Ukraine: "uk-UA",
    Ukrainian: "uk",
    Urdu_India: "ur-IN",
    Urdu_Pakistan: "ur-PK",
    Urdu: "ur",
    Uzbek_Arabic: "uz-Arab",
    Uzbek_Arabic_Afghanistan: "uz-Arab-AF",
    Uzbek_Cyrillic: "uz-Cyrl",
    Uzbek_Cyrillic_Uzbekistan: "uz-Cyrl-UZ",
    Uzbek_Latin: "uz-Latn",
    Uzbek_Latin_Uzbekistan: "uz-Latn-UZ",
    Uzbek: "uz",
    Vietnamese_Vietnam: "vi-VN",
    Vietnamese: "vi",
    Vunjo_Tanzania: "vun-TZ",
    Vunjo: "vun",
    Welsh_United_Kingdom: "cy-GB",
    Welsh: "cy",
    Yoruba_Nigeria: "yo-NG",
    Yoruba: "yo",
    Zulu_South_Africa: "zu-ZA",
    Zulu: "zu"
};

const CODE_BY_LANGUAGE = {
    Afrikaans: "afr",
    ASL: "ase",
    Apache: "apw",
    Aymara: "aym",
    Indonesian: "ind",
    Malay: "msa",
    Tzotzil: "tzo",
    Bikolano: "bik",
    Bislama: "bis",
    Kaqchikel: "cak",
    Cakchiquel: "cak",
    Catalan: "cat",
    Cebuano: "ceb",
    Czech: "ces",
    Danish: "dan",
    German: "deu",
    Navajo: "nav",
    Kuna: "cuk",
    Yoruba: "yor",
    Estonian: "est",
    Efik: "efi",
    Kisii: "guz",
    English: "eng",
    Spanish: "spa",
    Basque: "eus",
    Tongan: "ton",
    Fante: "fat",
    HindiFiji: "hif",
    Chuukese: "chk",
    French: "fra",
    Samoan: "smo",
    Guarani: "grn",
    Hiligaynon: "hil",
    HiriMotu: "hmo",
    Hmong: "hmn",
    Croatian: "hrv",
    Igbo: "ibo",
    Ilokano: "ilo",
    Icelandic: "isl",
    Italian: "ita",
    Kosraean: "kos",
    Marshallese: "mah",
    QuichuaEcuador: "qvi",
    Kamba: "kam",
    Kinyarwanda: "kin",
    Kiribati: "gil",
    Swahili: "swa",
    HaitianCreole: "hat",
    Latvian: "lav",
    Lithuanian: "lit",
    Lingala: "lin",
    Hungarian: "hun",
    Pohnpeian: "pon",
    Malagasy: "mlg",
    Maltese: "mlt",
    Mam: "mam",
    Rarotongan: "rar",
    Dutch: "nld",
    Chulupi: "cag",
    Norwegian: "nor",
    Palauan: "pau",
    Pampango: "pam",
    Pangasinan: "pag",
    Papiamento: "pap",
    Polish: "pol",
    Brasil: "por",
    Portuguese: "por",
    Portugal: "ept",
    EuroPortuguese: "ept",
    Kekchi: "kek",
    QuechuaBolivia: "quh",
    Quiche: "quc",
    Tahitian: "tah",
    Romanian: "ron",
    Tswana: "tsn",
    Shona: "sna",
    Albanian: "alb",
    Slovak: "slk",
    Slovenian: "slv",
    SouthSotho: "sot",
    Finnish: "fin",
    Swedish: "swe",
    Tagalog: "tgl",
    Yapese: "yap",
    Vietnamese: "vie",
    TokPisin: "tpi",
    Turkish: "tur",
    Twi: "twi",
    Fijian: "fij",
    Waray: "war",
    Xhosa: "xho",
    QuechuaPeru: "quz",
    Zulu: "zul",
    Greek: "ell",
    Bulgarian: "bul",
    Kazakh: "kaz",
    Macedonian: "mkd",
    Mongolian: "mon",
    Russian: "rus",
    Serbian: "srp",
    Ukrainian: "ukr",
    Georgian: "kat",
    Armenian: "hye",
    Urdu: "urd",
    Arabic: "ara",
    Persian: "pes",
    Farsi: "pes",
    Amharic: "amh",
    Nepali: "nep",
    Hindi: "hin",
    Bengali: "ben",
    Tamil: "tam",
    Telugu: "tel",
    Sinhala: "sin",
    Thai: "tha",
    Laotian: "lao",
    Burmese: "mya",
    Cambodian: "khm",
    Korean: "kor",
    Chinese: "zho",
    Japanese: "jpn",
    SimplifiedChinese: "zhs"
};

const LANGUAGE_BY_CODE = {
    afr: "Afrikaans",
    ase: "ASL",
    apw: "Apache",
    aym: "Aymara",
    ind: "Indonesian",
    msa: "Malay",
    tzo: "Tzotzil",
    bik: "Bikolano",
    bis: "Bislama",
    cak: {lang1: "Kaqchikel", lang2: "Cakchiquel"},
    cat: "Catalan",
    ceb: "Cebuano",
    ces: "Czech",
    dan: "Danish",
    deu: "German",
    nav: "Navajo",
    cuk: "Kuna",
    yor: "Yoruba",
    est: "Estonian",
    efi: "Efik",
    guz: "Kisii",
    eng: "English",
    spa: "Spanish",
    eus: "Basque",
    ton: "Tongan",
    fat: "Fante",
    hif: "HindiFiji",
    chk: "Chuukese",
    fra: "French",
    smo: "Samoan",
    grn: "Guarani",
    hil: "Hiligaynon",
    hmo: "HiriMotu",
    hmn: "Hmong",
    hrv: "Croatian",
    ibo: "Igbo",
    ilo: "Ilokano",
    isl: "Icelandic",
    ita: "Italian",
    kos: "Kosraean",
    mah: "Marshallese",
    qvi: "QuichuaEcuador",
    kam: "Kamba",
    kin: "Kinyarwanda",
    gil: "Kiribati",
    swa: "Swahili",
    hat: "HaitianCreole",
    lav: "Latvian",
    lit: "Lithuanian",
    lin: "Lingala",
    hun: "Hungarian",
    pon: "Pohnpeian",
    mlg: "Malagasy",
    mlt: "Maltese",
    mam: "Mam",
    rar: "Rarotongan",
    nld: "Dutch",
    cag: "Chulupi",
    nor: "Norwegian",
    pau: "Palauan",
    pam: "Pampango",
    pag: "Pangasinan",
    pap: "Papiamento",
    pol: "Polish",
    por: "Brasil",
    ept: "Portugal",
    kek: "Kekchi",
    quh: "QuechuaBolivia",
    quc: "Quiche",
    tah: "Tahitian",
    ron: "Romanian",
    tsn: "Tswana",
    sna: "Shona",
    alb: "Albanian",
    slk: "Slovak",
    slv: "Slovenian",
    sot: "SouthSotho",
    fin: "Finnish",
    swe: "Swedish",
    tgl: "Tagalog",
    yap: "Yapese",
    vie: "Vietnamese",
    tpi: "TokPisin",
    tur: "Turkish",
    twi: "Twi",
    fij: "Fijian",
    war: "Waray",
    xho: "Xhosa",
    quz: "QuechuaPeru",
    zul: "Zulu",
    ell: "Greek",
    bul: "Bulgarian",
    kaz: "Kazakh",
    mkd: "Macedonian",
    mon: "Mongolian",
    rus: "Russian",
    srp: "Serbian",
    ukr: "Ukrainian",
    kat: "Georgian",
    hye: "Armenian",
    urd: "Urdu",
    ara: "Arabic",
    pes: {lang1: "Persian", lang2: "Farsi"},
    amh: "Amharic",
    nep: "Nepali",
    hin: "Hindi",
    ben: "Bengali",
    tam: "Tamil",
    tel: "Telugu",
    sin: "Sinhala",
    tha: "Thai",
    lao: "Laotian",
    mya: "Burmese",
    khm: "Cambodian",
    kor: "Korean",
    zho: "Chinese",
    jpn: "Japanese",
    zhs: "SimplifiedChinese"
};

module.exports = {
    LANGUAGE_BY_LOCALE,
    LOCALE_BY_LANGUAGE,
    CODE_BY_LANGUAGE,
    LANGUAGE_BY_CODE,
    languageFromlang3,
    lang3FromLocale,
    localeFromLang3
};